// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FullUserProto.proto

package com.lvl6.mobsters.noneventprotos;

public final class FullUser {
  private FullUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FullUserProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string userID = 1;
    boolean hasUserID();
    String getUserID();
    
    // optional int32 level = 2;
    boolean hasLevel();
    int getLevel();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // optional int32 exp = 4;
    boolean hasExp();
    int getExp();
    
    // optional int32 gold = 5;
    boolean hasGold();
    int getGold();
    
    // optional int32 tonic = 6;
    boolean hasTonic();
    int getTonic();
    
    // optional int32 gems = 7;
    boolean hasGems();
    int getGems();
    
    // required .proto.ClassType classType = 8;
    boolean hasClassType();
    com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType getClassType();
    
    // optional int32 lastHealth = 9;
    boolean hasLastHealth();
    int getLastHealth();
    
    // optional int32 maxHealth = 10;
    boolean hasMaxHealth();
    int getMaxHealth();
    
    // optional int64 lastHealthRegen = 11;
    boolean hasLastHealthRegen();
    long getLastHealthRegen();
    
    // optional int32 lastMana = 12;
    boolean hasLastMana();
    int getLastMana();
    
    // optional int32 maxMana = 13;
    boolean hasMaxMana();
    int getMaxMana();
    
    // optional int64 lastManaRecovery = 14;
    boolean hasLastManaRecovery();
    long getLastManaRecovery();
    
    // optional string gameCenterID = 15;
    boolean hasGameCenterID();
    String getGameCenterID();
    
    // optional int64 dateCreated = 16;
    boolean hasDateCreated();
    long getDateCreated();
    
    // optional string clanID = 17;
    boolean hasClanID();
    String getClanID();
  }
  public static final class FullUserProto extends
      com.google.protobuf.GeneratedMessage
      implements FullUserProtoOrBuilder {
    // Use FullUserProto.newBuilder() to construct.
    private FullUserProto(Builder builder) {
      super(builder);
    }
    private FullUserProto(boolean noInit) {}
    
    private static final FullUserProto defaultInstance;
    public static FullUserProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public FullUserProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_FullUserProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_FullUserProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string userID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userID_;
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserID() {
      java.lang.Object ref = userID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLevel() {
      return level_;
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 exp = 4;
    public static final int EXP_FIELD_NUMBER = 4;
    private int exp_;
    public boolean hasExp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getExp() {
      return exp_;
    }
    
    // optional int32 gold = 5;
    public static final int GOLD_FIELD_NUMBER = 5;
    private int gold_;
    public boolean hasGold() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getGold() {
      return gold_;
    }
    
    // optional int32 tonic = 6;
    public static final int TONIC_FIELD_NUMBER = 6;
    private int tonic_;
    public boolean hasTonic() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getTonic() {
      return tonic_;
    }
    
    // optional int32 gems = 7;
    public static final int GEMS_FIELD_NUMBER = 7;
    private int gems_;
    public boolean hasGems() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getGems() {
      return gems_;
    }
    
    // required .proto.ClassType classType = 8;
    public static final int CLASSTYPE_FIELD_NUMBER = 8;
    private com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType classType_;
    public boolean hasClassType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType getClassType() {
      return classType_;
    }
    
    // optional int32 lastHealth = 9;
    public static final int LASTHEALTH_FIELD_NUMBER = 9;
    private int lastHealth_;
    public boolean hasLastHealth() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getLastHealth() {
      return lastHealth_;
    }
    
    // optional int32 maxHealth = 10;
    public static final int MAXHEALTH_FIELD_NUMBER = 10;
    private int maxHealth_;
    public boolean hasMaxHealth() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getMaxHealth() {
      return maxHealth_;
    }
    
    // optional int64 lastHealthRegen = 11;
    public static final int LASTHEALTHREGEN_FIELD_NUMBER = 11;
    private long lastHealthRegen_;
    public boolean hasLastHealthRegen() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getLastHealthRegen() {
      return lastHealthRegen_;
    }
    
    // optional int32 lastMana = 12;
    public static final int LASTMANA_FIELD_NUMBER = 12;
    private int lastMana_;
    public boolean hasLastMana() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getLastMana() {
      return lastMana_;
    }
    
    // optional int32 maxMana = 13;
    public static final int MAXMANA_FIELD_NUMBER = 13;
    private int maxMana_;
    public boolean hasMaxMana() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getMaxMana() {
      return maxMana_;
    }
    
    // optional int64 lastManaRecovery = 14;
    public static final int LASTMANARECOVERY_FIELD_NUMBER = 14;
    private long lastManaRecovery_;
    public boolean hasLastManaRecovery() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public long getLastManaRecovery() {
      return lastManaRecovery_;
    }
    
    // optional string gameCenterID = 15;
    public static final int GAMECENTERID_FIELD_NUMBER = 15;
    private java.lang.Object gameCenterID_;
    public boolean hasGameCenterID() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getGameCenterID() {
      java.lang.Object ref = gameCenterID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameCenterID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameCenterIDBytes() {
      java.lang.Object ref = gameCenterID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameCenterID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 dateCreated = 16;
    public static final int DATECREATED_FIELD_NUMBER = 16;
    private long dateCreated_;
    public boolean hasDateCreated() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public long getDateCreated() {
      return dateCreated_;
    }
    
    // optional string clanID = 17;
    public static final int CLANID_FIELD_NUMBER = 17;
    private java.lang.Object clanID_;
    public boolean hasClanID() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public String getClanID() {
      java.lang.Object ref = clanID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clanID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClanIDBytes() {
      java.lang.Object ref = clanID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clanID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userID_ = "";
      level_ = 0;
      name_ = "";
      exp_ = 0;
      gold_ = 0;
      tonic_ = 0;
      gems_ = 0;
      classType_ = com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType.WARRIOR;
      lastHealth_ = 0;
      maxHealth_ = 0;
      lastHealthRegen_ = 0L;
      lastMana_ = 0;
      maxMana_ = 0;
      lastManaRecovery_ = 0L;
      gameCenterID_ = "";
      dateCreated_ = 0L;
      clanID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClassType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, exp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, tonic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, gems_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, classType_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, lastHealth_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, maxHealth_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, lastHealthRegen_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, lastMana_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, maxMana_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, lastManaRecovery_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getGameCenterIDBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt64(16, dateCreated_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getClanIDBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, tonic_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, gems_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, classType_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, lastHealth_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, maxHealth_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, lastHealthRegen_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, lastMana_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, maxMana_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, lastManaRecovery_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getGameCenterIDBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, dateCreated_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getClanIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_FullUserProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_FullUserProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        tonic_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        gems_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        classType_ = com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType.WARRIOR;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastHealth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        maxHealth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        lastHealthRegen_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        lastMana_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        maxMana_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        lastManaRecovery_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        gameCenterID_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        dateCreated_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        clanID_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto build() {
        com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto buildPartial() {
        com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto result = new com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tonic_ = tonic_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gems_ = gems_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.classType_ = classType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastHealth_ = lastHealth_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.maxHealth_ = maxHealth_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lastHealthRegen_ = lastHealthRegen_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.lastMana_ = lastMana_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.maxMana_ = maxMana_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.lastManaRecovery_ = lastManaRecovery_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.gameCenterID_ = gameCenterID_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.dateCreated_ = dateCreated_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.clanID_ = clanID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto) {
          return mergeFrom((com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto other) {
        if (other == com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance()) return this;
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasTonic()) {
          setTonic(other.getTonic());
        }
        if (other.hasGems()) {
          setGems(other.getGems());
        }
        if (other.hasClassType()) {
          setClassType(other.getClassType());
        }
        if (other.hasLastHealth()) {
          setLastHealth(other.getLastHealth());
        }
        if (other.hasMaxHealth()) {
          setMaxHealth(other.getMaxHealth());
        }
        if (other.hasLastHealthRegen()) {
          setLastHealthRegen(other.getLastHealthRegen());
        }
        if (other.hasLastMana()) {
          setLastMana(other.getLastMana());
        }
        if (other.hasMaxMana()) {
          setMaxMana(other.getMaxMana());
        }
        if (other.hasLastManaRecovery()) {
          setLastManaRecovery(other.getLastManaRecovery());
        }
        if (other.hasGameCenterID()) {
          setGameCenterID(other.getGameCenterID());
        }
        if (other.hasDateCreated()) {
          setDateCreated(other.getDateCreated());
        }
        if (other.hasClanID()) {
          setClanID(other.getClanID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClassType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              exp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gold_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tonic_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              gems_ = input.readInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType value = com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                classType_ = value;
              }
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              lastHealth_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              maxHealth_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              lastHealthRegen_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              lastMana_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              maxMana_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              lastManaRecovery_ = input.readInt64();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              gameCenterID_ = input.readBytes();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              dateCreated_ = input.readInt64();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              clanID_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string userID = 1;
      private java.lang.Object userID_ = "";
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserID() {
        java.lang.Object ref = userID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = getDefaultInstance().getUserID();
        onChanged();
        return this;
      }
      void setUserID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
      }
      
      // optional int32 level = 2;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // optional int32 exp = 4;
      private int exp_ ;
      public boolean hasExp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getExp() {
        return exp_;
      }
      public Builder setExp(int value) {
        bitField0_ |= 0x00000008;
        exp_ = value;
        onChanged();
        return this;
      }
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gold = 5;
      private int gold_ ;
      public boolean hasGold() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getGold() {
        return gold_;
      }
      public Builder setGold(int value) {
        bitField0_ |= 0x00000010;
        gold_ = value;
        onChanged();
        return this;
      }
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gold_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 tonic = 6;
      private int tonic_ ;
      public boolean hasTonic() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getTonic() {
        return tonic_;
      }
      public Builder setTonic(int value) {
        bitField0_ |= 0x00000020;
        tonic_ = value;
        onChanged();
        return this;
      }
      public Builder clearTonic() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tonic_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gems = 7;
      private int gems_ ;
      public boolean hasGems() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getGems() {
        return gems_;
      }
      public Builder setGems(int value) {
        bitField0_ |= 0x00000040;
        gems_ = value;
        onChanged();
        return this;
      }
      public Builder clearGems() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gems_ = 0;
        onChanged();
        return this;
      }
      
      // required .proto.ClassType classType = 8;
      private com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType classType_ = com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType.WARRIOR;
      public boolean hasClassType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType getClassType() {
        return classType_;
      }
      public Builder setClassType(com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        classType_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        classType_ = com.lvl6.mobsters.noneventprotos.ClassEnum.ClassType.WARRIOR;
        onChanged();
        return this;
      }
      
      // optional int32 lastHealth = 9;
      private int lastHealth_ ;
      public boolean hasLastHealth() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getLastHealth() {
        return lastHealth_;
      }
      public Builder setLastHealth(int value) {
        bitField0_ |= 0x00000100;
        lastHealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastHealth() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastHealth_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 maxHealth = 10;
      private int maxHealth_ ;
      public boolean hasMaxHealth() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getMaxHealth() {
        return maxHealth_;
      }
      public Builder setMaxHealth(int value) {
        bitField0_ |= 0x00000200;
        maxHealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxHealth() {
        bitField0_ = (bitField0_ & ~0x00000200);
        maxHealth_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 lastHealthRegen = 11;
      private long lastHealthRegen_ ;
      public boolean hasLastHealthRegen() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getLastHealthRegen() {
        return lastHealthRegen_;
      }
      public Builder setLastHealthRegen(long value) {
        bitField0_ |= 0x00000400;
        lastHealthRegen_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastHealthRegen() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lastHealthRegen_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 lastMana = 12;
      private int lastMana_ ;
      public boolean hasLastMana() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getLastMana() {
        return lastMana_;
      }
      public Builder setLastMana(int value) {
        bitField0_ |= 0x00000800;
        lastMana_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastMana() {
        bitField0_ = (bitField0_ & ~0x00000800);
        lastMana_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 maxMana = 13;
      private int maxMana_ ;
      public boolean hasMaxMana() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getMaxMana() {
        return maxMana_;
      }
      public Builder setMaxMana(int value) {
        bitField0_ |= 0x00001000;
        maxMana_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxMana() {
        bitField0_ = (bitField0_ & ~0x00001000);
        maxMana_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 lastManaRecovery = 14;
      private long lastManaRecovery_ ;
      public boolean hasLastManaRecovery() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public long getLastManaRecovery() {
        return lastManaRecovery_;
      }
      public Builder setLastManaRecovery(long value) {
        bitField0_ |= 0x00002000;
        lastManaRecovery_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastManaRecovery() {
        bitField0_ = (bitField0_ & ~0x00002000);
        lastManaRecovery_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string gameCenterID = 15;
      private java.lang.Object gameCenterID_ = "";
      public boolean hasGameCenterID() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getGameCenterID() {
        java.lang.Object ref = gameCenterID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameCenterID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameCenterID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        gameCenterID_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameCenterID() {
        bitField0_ = (bitField0_ & ~0x00004000);
        gameCenterID_ = getDefaultInstance().getGameCenterID();
        onChanged();
        return this;
      }
      void setGameCenterID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        gameCenterID_ = value;
        onChanged();
      }
      
      // optional int64 dateCreated = 16;
      private long dateCreated_ ;
      public boolean hasDateCreated() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public long getDateCreated() {
        return dateCreated_;
      }
      public Builder setDateCreated(long value) {
        bitField0_ |= 0x00008000;
        dateCreated_ = value;
        onChanged();
        return this;
      }
      public Builder clearDateCreated() {
        bitField0_ = (bitField0_ & ~0x00008000);
        dateCreated_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string clanID = 17;
      private java.lang.Object clanID_ = "";
      public boolean hasClanID() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public String getClanID() {
        java.lang.Object ref = clanID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clanID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClanID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        clanID_ = value;
        onChanged();
        return this;
      }
      public Builder clearClanID() {
        bitField0_ = (bitField0_ & ~0x00010000);
        clanID_ = getDefaultInstance().getClanID();
        onChanged();
        return this;
      }
      void setClanID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00010000;
        clanID_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.FullUserProto)
    }
    
    static {
      defaultInstance = new FullUserProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.FullUserProto)
  }
  
  public interface MinimumUserProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string userID = 1;
    boolean hasUserID();
    String getUserID();
    
    // optional string gameCenterId = 2;
    boolean hasGameCenterId();
    String getGameCenterId();
    
    // optional string udid = 3;
    boolean hasUdid();
    String getUdid();
    
    // optional string name = 4;
    boolean hasName();
    String getName();
  }
  public static final class MinimumUserProto extends
      com.google.protobuf.GeneratedMessage
      implements MinimumUserProtoOrBuilder {
    // Use MinimumUserProto.newBuilder() to construct.
    private MinimumUserProto(Builder builder) {
      super(builder);
    }
    private MinimumUserProto(boolean noInit) {}
    
    private static final MinimumUserProto defaultInstance;
    public static MinimumUserProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public MinimumUserProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_MinimumUserProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_MinimumUserProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string userID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userID_;
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserID() {
      java.lang.Object ref = userID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string gameCenterId = 2;
    public static final int GAMECENTERID_FIELD_NUMBER = 2;
    private java.lang.Object gameCenterId_;
    public boolean hasGameCenterId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getGameCenterId() {
      java.lang.Object ref = gameCenterId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameCenterId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameCenterIdBytes() {
      java.lang.Object ref = gameCenterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameCenterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string udid = 3;
    public static final int UDID_FIELD_NUMBER = 3;
    private java.lang.Object udid_;
    public boolean hasUdid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          udid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userID_ = "";
      gameCenterId_ = "";
      udid_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGameCenterIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUdidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGameCenterIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUdidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_MinimumUserProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.noneventprotos.FullUser.internal_static_proto_MinimumUserProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        gameCenterId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        udid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto build() {
        com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto buildPartial() {
        com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto result = new com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameCenterId_ = gameCenterId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.udid_ = udid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto) {
          return mergeFrom((com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto other) {
        if (other == com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) return this;
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        if (other.hasGameCenterId()) {
          setGameCenterId(other.getGameCenterId());
        }
        if (other.hasUdid()) {
          setUdid(other.getUdid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              gameCenterId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              udid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string userID = 1;
      private java.lang.Object userID_ = "";
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserID() {
        java.lang.Object ref = userID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = getDefaultInstance().getUserID();
        onChanged();
        return this;
      }
      void setUserID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
      }
      
      // optional string gameCenterId = 2;
      private java.lang.Object gameCenterId_ = "";
      public boolean hasGameCenterId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getGameCenterId() {
        java.lang.Object ref = gameCenterId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameCenterId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameCenterId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        gameCenterId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameCenterId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameCenterId_ = getDefaultInstance().getGameCenterId();
        onChanged();
        return this;
      }
      void setGameCenterId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        gameCenterId_ = value;
        onChanged();
      }
      
      // optional string udid = 3;
      private java.lang.Object udid_ = "";
      public boolean hasUdid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          udid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUdid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        udid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUdid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      void setUdid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        udid_ = value;
        onChanged();
      }
      
      // optional string name = 4;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.MinimumUserProto)
    }
    
    static {
      defaultInstance = new MinimumUserProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.MinimumUserProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FullUserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_FullUserProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MinimumUserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MinimumUserProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FullUserProto.proto\022\005proto\032\017ClassType." +
      "proto\"\321\002\n\rFullUserProto\022\016\n\006userID\030\001 \001(\t\022" +
      "\r\n\005level\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\013\n\003exp\030\004 \001(" +
      "\005\022\014\n\004gold\030\005 \001(\005\022\r\n\005tonic\030\006 \001(\005\022\014\n\004gems\030\007" +
      " \001(\005\022#\n\tclassType\030\010 \002(\0162\020.proto.ClassTyp" +
      "e\022\022\n\nlastHealth\030\t \001(\005\022\021\n\tmaxHealth\030\n \001(\005" +
      "\022\027\n\017lastHealthRegen\030\013 \001(\003\022\020\n\010lastMana\030\014 " +
      "\001(\005\022\017\n\007maxMana\030\r \001(\005\022\030\n\020lastManaRecovery" +
      "\030\016 \001(\003\022\024\n\014gameCenterID\030\017 \001(\t\022\023\n\013dateCrea" +
      "ted\030\020 \001(\003\022\016\n\006clanID\030\021 \001(\t\"T\n\020MinimumUser",
      "Proto\022\016\n\006userID\030\001 \001(\t\022\024\n\014gameCenterId\030\002 " +
      "\001(\t\022\014\n\004udid\030\003 \001(\t\022\014\n\004name\030\004 \001(\tB(\n\034com.l" +
      "vl6.aoc2.noneventprotosB\010FullUser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_FullUserProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_FullUserProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_FullUserProto_descriptor,
              new java.lang.String[] { "UserID", "Level", "Name", "Exp", "Gold", "Tonic", "Gems", "ClassType", "LastHealth", "MaxHealth", "LastHealthRegen", "LastMana", "MaxMana", "LastManaRecovery", "GameCenterID", "DateCreated", "ClanID", },
              com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.class,
              com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder.class);
          internal_static_proto_MinimumUserProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_MinimumUserProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_MinimumUserProto_descriptor,
              new java.lang.String[] { "UserID", "GameCenterId", "Udid", "Name", },
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.class,
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.ClassEnum.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
