// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonsterProto.proto

package com.lvl6.mobsters.noneventprotos;

public final class Monster {
  private Monster() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MonsterProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 monsterID = 1;
    boolean hasMonsterID();
    int getMonsterID();
    
    // optional int32 maxHealth = 2;
    boolean hasMaxHealth();
    int getMaxHealth();
    
    // optional int32 maxMana = 3;
    boolean hasMaxMana();
    int getMaxMana();
    
    // optional int32 attack = 4;
    boolean hasAttack();
    int getAttack();
    
    // optional int32 defense = 5;
    boolean hasDefense();
    int getDefense();
    
    // required .proto.MonsterType type = 6;
    boolean hasType();
    com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType getType();
    
    // optional .proto.ColorProto color = 7;
    boolean hasColor();
    com.lvl6.mobsters.noneventprotos.Color.ColorProto getColor();
    com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder getColorOrBuilder();
    
    // optional float size = 8;
    boolean hasSize();
    float getSize();
    
    // optional int32 experience = 9;
    boolean hasExperience();
    int getExperience();
    
    // optional bool isBoss = 10;
    boolean hasIsBoss();
    boolean getIsBoss();
  }
  public static final class MonsterProto extends
      com.google.protobuf.GeneratedMessage
      implements MonsterProtoOrBuilder {
    // Use MonsterProto.newBuilder() to construct.
    private MonsterProto(Builder builder) {
      super(builder);
    }
    private MonsterProto(boolean noInit) {}
    
    private static final MonsterProto defaultInstance;
    public static MonsterProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public MonsterProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.noneventprotos.Monster.internal_static_proto_MonsterProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.noneventprotos.Monster.internal_static_proto_MonsterProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 monsterID = 1;
    public static final int MONSTERID_FIELD_NUMBER = 1;
    private int monsterID_;
    public boolean hasMonsterID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMonsterID() {
      return monsterID_;
    }
    
    // optional int32 maxHealth = 2;
    public static final int MAXHEALTH_FIELD_NUMBER = 2;
    private int maxHealth_;
    public boolean hasMaxHealth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMaxHealth() {
      return maxHealth_;
    }
    
    // optional int32 maxMana = 3;
    public static final int MAXMANA_FIELD_NUMBER = 3;
    private int maxMana_;
    public boolean hasMaxMana() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getMaxMana() {
      return maxMana_;
    }
    
    // optional int32 attack = 4;
    public static final int ATTACK_FIELD_NUMBER = 4;
    private int attack_;
    public boolean hasAttack() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getAttack() {
      return attack_;
    }
    
    // optional int32 defense = 5;
    public static final int DEFENSE_FIELD_NUMBER = 5;
    private int defense_;
    public boolean hasDefense() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getDefense() {
      return defense_;
    }
    
    // required .proto.MonsterType type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType getType() {
      return type_;
    }
    
    // optional .proto.ColorProto color = 7;
    public static final int COLOR_FIELD_NUMBER = 7;
    private com.lvl6.mobsters.noneventprotos.Color.ColorProto color_;
    public boolean hasColor() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.lvl6.mobsters.noneventprotos.Color.ColorProto getColor() {
      return color_;
    }
    public com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder getColorOrBuilder() {
      return color_;
    }
    
    // optional float size = 8;
    public static final int SIZE_FIELD_NUMBER = 8;
    private float size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public float getSize() {
      return size_;
    }
    
    // optional int32 experience = 9;
    public static final int EXPERIENCE_FIELD_NUMBER = 9;
    private int experience_;
    public boolean hasExperience() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getExperience() {
      return experience_;
    }
    
    // optional bool isBoss = 10;
    public static final int ISBOSS_FIELD_NUMBER = 10;
    private boolean isBoss_;
    public boolean hasIsBoss() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public boolean getIsBoss() {
      return isBoss_;
    }
    
    private void initFields() {
      monsterID_ = 0;
      maxHealth_ = 0;
      maxMana_ = 0;
      attack_ = 0;
      defense_ = 0;
      type_ = com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType.GOBLIN;
      color_ = com.lvl6.mobsters.noneventprotos.Color.ColorProto.getDefaultInstance();
      size_ = 0F;
      experience_ = 0;
      isBoss_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, monsterID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxHealth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maxMana_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, attack_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, defense_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, type_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, color_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, size_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, experience_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(10, isBoss_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, monsterID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxHealth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxMana_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, attack_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, defense_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, color_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, size_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, experience_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isBoss_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.noneventprotos.Monster.MonsterProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.noneventprotos.Monster.MonsterProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.noneventprotos.Monster.MonsterProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.noneventprotos.Monster.internal_static_proto_MonsterProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.noneventprotos.Monster.internal_static_proto_MonsterProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        monsterID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxHealth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxMana_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        attack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        defense_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType.GOBLIN;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (colorBuilder_ == null) {
          color_ = com.lvl6.mobsters.noneventprotos.Color.ColorProto.getDefaultInstance();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        size_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        experience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        isBoss_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.noneventprotos.Monster.MonsterProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.noneventprotos.Monster.MonsterProto build() {
        com.lvl6.mobsters.noneventprotos.Monster.MonsterProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.noneventprotos.Monster.MonsterProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.noneventprotos.Monster.MonsterProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.noneventprotos.Monster.MonsterProto buildPartial() {
        com.lvl6.mobsters.noneventprotos.Monster.MonsterProto result = new com.lvl6.mobsters.noneventprotos.Monster.MonsterProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.monsterID_ = monsterID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxHealth_ = maxHealth_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxMana_ = maxMana_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attack_ = attack_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.defense_ = defense_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (colorBuilder_ == null) {
          result.color_ = color_;
        } else {
          result.color_ = colorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.experience_ = experience_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.isBoss_ = isBoss_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.noneventprotos.Monster.MonsterProto) {
          return mergeFrom((com.lvl6.mobsters.noneventprotos.Monster.MonsterProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.noneventprotos.Monster.MonsterProto other) {
        if (other == com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.getDefaultInstance()) return this;
        if (other.hasMonsterID()) {
          setMonsterID(other.getMonsterID());
        }
        if (other.hasMaxHealth()) {
          setMaxHealth(other.getMaxHealth());
        }
        if (other.hasMaxMana()) {
          setMaxMana(other.getMaxMana());
        }
        if (other.hasAttack()) {
          setAttack(other.getAttack());
        }
        if (other.hasDefense()) {
          setDefense(other.getDefense());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasExperience()) {
          setExperience(other.getExperience());
        }
        if (other.hasIsBoss()) {
          setIsBoss(other.getIsBoss());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              monsterID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxHealth_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxMana_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              attack_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              defense_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType value = com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                type_ = value;
              }
              break;
            }
            case 58: {
              com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.Color.ColorProto.newBuilder();
              if (hasColor()) {
                subBuilder.mergeFrom(getColor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setColor(subBuilder.buildPartial());
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              size_ = input.readFloat();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              experience_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              isBoss_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 monsterID = 1;
      private int monsterID_ ;
      public boolean hasMonsterID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMonsterID() {
        return monsterID_;
      }
      public Builder setMonsterID(int value) {
        bitField0_ |= 0x00000001;
        monsterID_ = value;
        onChanged();
        return this;
      }
      public Builder clearMonsterID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        monsterID_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 maxHealth = 2;
      private int maxHealth_ ;
      public boolean hasMaxHealth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMaxHealth() {
        return maxHealth_;
      }
      public Builder setMaxHealth(int value) {
        bitField0_ |= 0x00000002;
        maxHealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxHealth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxHealth_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 maxMana = 3;
      private int maxMana_ ;
      public boolean hasMaxMana() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getMaxMana() {
        return maxMana_;
      }
      public Builder setMaxMana(int value) {
        bitField0_ |= 0x00000004;
        maxMana_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxMana() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxMana_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 attack = 4;
      private int attack_ ;
      public boolean hasAttack() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getAttack() {
        return attack_;
      }
      public Builder setAttack(int value) {
        bitField0_ |= 0x00000008;
        attack_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttack() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attack_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 defense = 5;
      private int defense_ ;
      public boolean hasDefense() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getDefense() {
        return defense_;
      }
      public Builder setDefense(int value) {
        bitField0_ |= 0x00000010;
        defense_ = value;
        onChanged();
        return this;
      }
      public Builder clearDefense() {
        bitField0_ = (bitField0_ & ~0x00000010);
        defense_ = 0;
        onChanged();
        return this;
      }
      
      // required .proto.MonsterType type = 6;
      private com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType type_ = com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType.GOBLIN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType getType() {
        return type_;
      }
      public Builder setType(com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = com.lvl6.mobsters.noneventprotos.MonsterEnum.MonsterType.GOBLIN;
        onChanged();
        return this;
      }
      
      // optional .proto.ColorProto color = 7;
      private com.lvl6.mobsters.noneventprotos.Color.ColorProto color_ = com.lvl6.mobsters.noneventprotos.Color.ColorProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.Color.ColorProto, com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder, com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder> colorBuilder_;
      public boolean hasColor() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.lvl6.mobsters.noneventprotos.Color.ColorProto getColor() {
        if (colorBuilder_ == null) {
          return color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      public Builder setColor(com.lvl6.mobsters.noneventprotos.Color.ColorProto value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
          onChanged();
        } else {
          colorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setColor(
          com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
          onChanged();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeColor(com.lvl6.mobsters.noneventprotos.Color.ColorProto value) {
        if (colorBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              color_ != com.lvl6.mobsters.noneventprotos.Color.ColorProto.getDefaultInstance()) {
            color_ =
              com.lvl6.mobsters.noneventprotos.Color.ColorProto.newBuilder(color_).mergeFrom(value).buildPartial();
          } else {
            color_ = value;
          }
          onChanged();
        } else {
          colorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearColor() {
        if (colorBuilder_ == null) {
          color_ = com.lvl6.mobsters.noneventprotos.Color.ColorProto.getDefaultInstance();
          onChanged();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder getColorBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getColorFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.Color.ColorProto, com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder, com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder> 
          getColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.Color.ColorProto, com.lvl6.mobsters.noneventprotos.Color.ColorProto.Builder, com.lvl6.mobsters.noneventprotos.Color.ColorProtoOrBuilder>(
                  color_,
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }
      
      // optional float size = 8;
      private float size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public float getSize() {
        return size_;
      }
      public Builder setSize(float value) {
        bitField0_ |= 0x00000080;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000080);
        size_ = 0F;
        onChanged();
        return this;
      }
      
      // optional int32 experience = 9;
      private int experience_ ;
      public boolean hasExperience() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getExperience() {
        return experience_;
      }
      public Builder setExperience(int value) {
        bitField0_ |= 0x00000100;
        experience_ = value;
        onChanged();
        return this;
      }
      public Builder clearExperience() {
        bitField0_ = (bitField0_ & ~0x00000100);
        experience_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool isBoss = 10;
      private boolean isBoss_ ;
      public boolean hasIsBoss() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public boolean getIsBoss() {
        return isBoss_;
      }
      public Builder setIsBoss(boolean value) {
        bitField0_ |= 0x00000200;
        isBoss_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsBoss() {
        bitField0_ = (bitField0_ & ~0x00000200);
        isBoss_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.MonsterProto)
    }
    
    static {
      defaultInstance = new MonsterProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.MonsterProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MonsterProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MonsterProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MonsterProto.proto\022\005proto\032\021MonsterType" +
      ".proto\032\020ColorProto.proto\"\334\001\n\014MonsterProt" +
      "o\022\021\n\tmonsterID\030\001 \001(\005\022\021\n\tmaxHealth\030\002 \001(\005\022" +
      "\017\n\007maxMana\030\003 \001(\005\022\016\n\006attack\030\004 \001(\005\022\017\n\007defe" +
      "nse\030\005 \001(\005\022 \n\004type\030\006 \002(\0162\022.proto.MonsterT" +
      "ype\022 \n\005color\030\007 \001(\0132\021.proto.ColorProto\022\014\n" +
      "\004size\030\010 \001(\002\022\022\n\nexperience\030\t \001(\005\022\016\n\006isBos" +
      "s\030\n \001(\010B\'\n\034com.lvl6.aoc2.noneventprotosB" +
      "\007Monster"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_MonsterProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_MonsterProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_MonsterProto_descriptor,
              new java.lang.String[] { "MonsterID", "MaxHealth", "MaxMana", "Attack", "Defense", "Type", "Color", "Size", "Experience", "IsBoss", },
              com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.class,
              com.lvl6.mobsters.noneventprotos.Monster.MonsterProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.MonsterEnum.getDescriptor(),
          com.lvl6.mobsters.noneventprotos.Color.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
