// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildOrUpgradeStructureEvent.proto

package com.lvl6.mobsters.eventprotos;

public final class BuildOrUpgradeStructureEventProto {
  private BuildOrUpgradeStructureEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ResourceCostType
      implements com.google.protobuf.ProtocolMessageEnum {
    GOLD(0, 0),
    TONIC(1, 1),
    ;
    
    public static final int GOLD_VALUE = 0;
    public static final int TONIC_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ResourceCostType valueOf(int value) {
      switch (value) {
        case 0: return GOLD;
        case 1: return TONIC;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ResourceCostType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResourceCostType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResourceCostType>() {
            public ResourceCostType findValueByNumber(int number) {
              return ResourceCostType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ResourceCostType[] VALUES = {
      GOLD, TONIC, 
    };
    
    public static ResourceCostType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ResourceCostType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.ResourceCostType)
  }
  
  public interface BuildOrUpgradeStructureRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional string userStructureId = 2;
    boolean hasUserStructureId();
    String getUserStructureId();
    
    // optional bool isBuild = 3;
    boolean hasIsBuild();
    boolean getIsBuild();
    
    // optional bool usingGems = 4;
    boolean hasUsingGems();
    boolean getUsingGems();
  }
  public static final class BuildOrUpgradeStructureRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements BuildOrUpgradeStructureRequestProtoOrBuilder {
    // Use BuildOrUpgradeStructureRequestProto.newBuilder() to construct.
    private BuildOrUpgradeStructureRequestProto(Builder builder) {
      super(builder);
    }
    private BuildOrUpgradeStructureRequestProto(boolean noInit) {}
    
    private static final BuildOrUpgradeStructureRequestProto defaultInstance;
    public static BuildOrUpgradeStructureRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuildOrUpgradeStructureRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional string userStructureId = 2;
    public static final int USERSTRUCTUREID_FIELD_NUMBER = 2;
    private java.lang.Object userStructureId_;
    public boolean hasUserStructureId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUserStructureId() {
      java.lang.Object ref = userStructureId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userStructureId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserStructureIdBytes() {
      java.lang.Object ref = userStructureId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userStructureId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool isBuild = 3;
    public static final int ISBUILD_FIELD_NUMBER = 3;
    private boolean isBuild_;
    public boolean hasIsBuild() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getIsBuild() {
      return isBuild_;
    }
    
    // optional bool usingGems = 4;
    public static final int USINGGEMS_FIELD_NUMBER = 4;
    private boolean usingGems_;
    public boolean hasUsingGems() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getUsingGems() {
      return usingGems_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      userStructureId_ = "";
      isBuild_ = false;
      usingGems_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserStructureIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isBuild_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, usingGems_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserStructureIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isBuild_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, usingGems_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        userStructureId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isBuild_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        usingGems_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto build() {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto buildPartial() {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto result = new com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userStructureId_ = userStructureId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isBuild_ = isBuild_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.usingGems_ = usingGems_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto other) {
        if (other == com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasUserStructureId()) {
          setUserStructureId(other.getUserStructureId());
        }
        if (other.hasIsBuild()) {
          setIsBuild(other.getIsBuild());
        }
        if (other.hasUsingGems()) {
          setUsingGems(other.getUsingGems());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userStructureId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isBuild_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              usingGems_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional string userStructureId = 2;
      private java.lang.Object userStructureId_ = "";
      public boolean hasUserStructureId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUserStructureId() {
        java.lang.Object ref = userStructureId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userStructureId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserStructureId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userStructureId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserStructureId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userStructureId_ = getDefaultInstance().getUserStructureId();
        onChanged();
        return this;
      }
      void setUserStructureId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        userStructureId_ = value;
        onChanged();
      }
      
      // optional bool isBuild = 3;
      private boolean isBuild_ ;
      public boolean hasIsBuild() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsBuild() {
        return isBuild_;
      }
      public Builder setIsBuild(boolean value) {
        bitField0_ |= 0x00000004;
        isBuild_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsBuild() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isBuild_ = false;
        onChanged();
        return this;
      }
      
      // optional bool usingGems = 4;
      private boolean usingGems_ ;
      public boolean hasUsingGems() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getUsingGems() {
        return usingGems_;
      }
      public Builder setUsingGems(boolean value) {
        bitField0_ |= 0x00000008;
        usingGems_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsingGems() {
        bitField0_ = (bitField0_ & ~0x00000008);
        usingGems_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.BuildOrUpgradeStructureRequestProto)
    }
    
    static {
      defaultInstance = new BuildOrUpgradeStructureRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.BuildOrUpgradeStructureRequestProto)
  }
  
  public interface BuildOrUpgradeStructureResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional .proto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus status = 2;
    boolean hasStatus();
    com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus getStatus();
  }
  public static final class BuildOrUpgradeStructureResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements BuildOrUpgradeStructureResponseProtoOrBuilder {
    // Use BuildOrUpgradeStructureResponseProto.newBuilder() to construct.
    private BuildOrUpgradeStructureResponseProto(Builder builder) {
      super(builder);
    }
    private BuildOrUpgradeStructureResponseProto(boolean noInit) {}
    
    private static final BuildOrUpgradeStructureResponseProto defaultInstance;
    public static BuildOrUpgradeStructureResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuildOrUpgradeStructureResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureResponseProto_fieldAccessorTable;
    }
    
    public enum BuildOrUpgradeStructureStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS(0, 0),
      FAIL_INSUFFICIENT_RESOURCES(1, 1),
      FAIL_NOT_AT_REQUIRED_LEVEL(2, 2),
      FAIL_MAXED_CONSTRUCTION(3, 3),
      FAIL_NO_STRUCTURE_EXISTS(4, 4),
      FAIL_RESTRICTION_ON_NUMBER_OF_STRUCTURES(5, 5),
      FAIL_STRUCTURE_AT_MAX_LEVEL(6, 6),
      FAIL_CANT_UPGRADE_WHILE_BUILDING(7, 7),
      FAIL_OTHER(8, 8),
      ;
      
      public static final int SUCCESS_VALUE = 0;
      public static final int FAIL_INSUFFICIENT_RESOURCES_VALUE = 1;
      public static final int FAIL_NOT_AT_REQUIRED_LEVEL_VALUE = 2;
      public static final int FAIL_MAXED_CONSTRUCTION_VALUE = 3;
      public static final int FAIL_NO_STRUCTURE_EXISTS_VALUE = 4;
      public static final int FAIL_RESTRICTION_ON_NUMBER_OF_STRUCTURES_VALUE = 5;
      public static final int FAIL_STRUCTURE_AT_MAX_LEVEL_VALUE = 6;
      public static final int FAIL_CANT_UPGRADE_WHILE_BUILDING_VALUE = 7;
      public static final int FAIL_OTHER_VALUE = 8;
      
      
      public final int getNumber() { return value; }
      
      public static BuildOrUpgradeStructureStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL_INSUFFICIENT_RESOURCES;
          case 2: return FAIL_NOT_AT_REQUIRED_LEVEL;
          case 3: return FAIL_MAXED_CONSTRUCTION;
          case 4: return FAIL_NO_STRUCTURE_EXISTS;
          case 5: return FAIL_RESTRICTION_ON_NUMBER_OF_STRUCTURES;
          case 6: return FAIL_STRUCTURE_AT_MAX_LEVEL;
          case 7: return FAIL_CANT_UPGRADE_WHILE_BUILDING;
          case 8: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<BuildOrUpgradeStructureStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BuildOrUpgradeStructureStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BuildOrUpgradeStructureStatus>() {
              public BuildOrUpgradeStructureStatus findValueByNumber(int number) {
                return BuildOrUpgradeStructureStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final BuildOrUpgradeStructureStatus[] VALUES = {
        SUCCESS, FAIL_INSUFFICIENT_RESOURCES, FAIL_NOT_AT_REQUIRED_LEVEL, FAIL_MAXED_CONSTRUCTION, FAIL_NO_STRUCTURE_EXISTS, FAIL_RESTRICTION_ON_NUMBER_OF_STRUCTURES, FAIL_STRUCTURE_AT_MAX_LEVEL, FAIL_CANT_UPGRADE_WHILE_BUILDING, FAIL_OTHER, 
      };
      
      public static BuildOrUpgradeStructureStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private BuildOrUpgradeStructureStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus)
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional .proto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      status_ = com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.internal_static_proto_BuildOrUpgradeStructureResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto build() {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto buildPartial() {
        com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto result = new com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto other) {
        if (other == com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus value = com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional .proto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus status = 2;
      private com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus status_ = com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus.SUCCESS;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.BuildOrUpgradeStructureStatus.SUCCESS;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.BuildOrUpgradeStructureResponseProto)
    }
    
    static {
      defaultInstance = new BuildOrUpgradeStructureResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.BuildOrUpgradeStructureResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BuildOrUpgradeStructureRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_BuildOrUpgradeStructureRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BuildOrUpgradeStructureResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_BuildOrUpgradeStructureResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"BuildOrUpgradeStructureEvent.proto\022\005pr" +
      "oto\032\023FullUserProto.proto\"\210\001\n#BuildOrUpgr" +
      "adeStructureRequestProto\022$\n\003mup\030\001 \001(\0132\027." +
      "proto.MinimumUserProto\022\027\n\017userStructureI" +
      "d\030\002 \001(\t\022\017\n\007isBuild\030\003 \001(\010\022\021\n\tusingGems\030\004 " +
      "\001(\010\"\327\003\n$BuildOrUpgradeStructureResponseP" +
      "roto\022$\n\003mup\030\001 \001(\0132\027.proto.MinimumUserPro" +
      "to\022Y\n\006status\030\002 \001(\0162I.proto.BuildOrUpgrad" +
      "eStructureResponseProto.BuildOrUpgradeSt" +
      "ructureStatus\"\255\002\n\035BuildOrUpgradeStructur",
      "eStatus\022\013\n\007SUCCESS\020\000\022\037\n\033FAIL_INSUFFICIEN" +
      "T_RESOURCES\020\001\022\036\n\032FAIL_NOT_AT_REQUIRED_LE" +
      "VEL\020\002\022\033\n\027FAIL_MAXED_CONSTRUCTION\020\003\022\034\n\030FA" +
      "IL_NO_STRUCTURE_EXISTS\020\004\022,\n(FAIL_RESTRIC" +
      "TION_ON_NUMBER_OF_STRUCTURES\020\005\022\037\n\033FAIL_S" +
      "TRUCTURE_AT_MAX_LEVEL\020\006\022$\n FAIL_CANT_UPG" +
      "RADE_WHILE_BUILDING\020\007\022\016\n\nFAIL_OTHER\020\010*\'\n" +
      "\020ResourceCostType\022\010\n\004GOLD\020\000\022\t\n\005TONIC\020\001B>" +
      "\n\031com.lvl6.aoc2.eventprotosB!BuildOrUpgr" +
      "adeStructureEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_BuildOrUpgradeStructureRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_BuildOrUpgradeStructureRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_BuildOrUpgradeStructureRequestProto_descriptor,
              new java.lang.String[] { "Mup", "UserStructureId", "IsBuild", "UsingGems", },
              com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.class,
              com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureRequestProto.Builder.class);
          internal_static_proto_BuildOrUpgradeStructureResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_BuildOrUpgradeStructureResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_BuildOrUpgradeStructureResponseProto_descriptor,
              new java.lang.String[] { "Mup", "Status", },
              com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.class,
              com.lvl6.mobsters.eventprotos.BuildOrUpgradeStructureEventProto.BuildOrUpgradeStructureResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.FullUser.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
