// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventStaticData.proto

package com.lvl6.mobsters.eventprotos;

public final class EventStaticDataProto {
  private EventStaticDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PurgeClientStaticDataResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 senderId = 1;
    boolean hasSenderId();
    int getSenderId();
    
    // optional .proto.StaticDataProto staticDataStuff = 2;
    boolean hasStaticDataStuff();
    com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto getStaticDataStuff();
    com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder getStaticDataStuffOrBuilder();
  }
  public static final class PurgeClientStaticDataResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements PurgeClientStaticDataResponseProtoOrBuilder {
    // Use PurgeClientStaticDataResponseProto.newBuilder() to construct.
    private PurgeClientStaticDataResponseProto(Builder builder) {
      super(builder);
    }
    private PurgeClientStaticDataResponseProto(boolean noInit) {}
    
    private static final PurgeClientStaticDataResponseProto defaultInstance;
    public static PurgeClientStaticDataResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public PurgeClientStaticDataResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.EventStaticDataProto.internal_static_proto_PurgeClientStaticDataResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.EventStaticDataProto.internal_static_proto_PurgeClientStaticDataResponseProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 senderId = 1;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderId_;
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSenderId() {
      return senderId_;
    }
    
    // optional .proto.StaticDataProto staticDataStuff = 2;
    public static final int STATICDATASTUFF_FIELD_NUMBER = 2;
    private com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto staticDataStuff_;
    public boolean hasStaticDataStuff() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto getStaticDataStuff() {
      return staticDataStuff_;
    }
    public com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder getStaticDataStuffOrBuilder() {
      return staticDataStuff_;
    }
    
    private void initFields() {
      senderId_ = 0;
      staticDataStuff_ = com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, senderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, staticDataStuff_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, staticDataStuff_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.EventStaticDataProto.internal_static_proto_PurgeClientStaticDataResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.EventStaticDataProto.internal_static_proto_PurgeClientStaticDataResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStaticDataStuffFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        senderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (staticDataStuffBuilder_ == null) {
          staticDataStuff_ = com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.getDefaultInstance();
        } else {
          staticDataStuffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto build() {
        com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto buildPartial() {
        com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto result = new com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (staticDataStuffBuilder_ == null) {
          result.staticDataStuff_ = staticDataStuff_;
        } else {
          result.staticDataStuff_ = staticDataStuffBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto other) {
        if (other == com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.getDefaultInstance()) return this;
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasStaticDataStuff()) {
          mergeStaticDataStuff(other.getStaticDataStuff());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              senderId_ = input.readInt32();
              break;
            }
            case 18: {
              com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.newBuilder();
              if (hasStaticDataStuff()) {
                subBuilder.mergeFrom(getStaticDataStuff());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStaticDataStuff(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 senderId = 1;
      private int senderId_ ;
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSenderId() {
        return senderId_;
      }
      public Builder setSenderId(int value) {
        bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = 0;
        onChanged();
        return this;
      }
      
      // optional .proto.StaticDataProto staticDataStuff = 2;
      private com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto staticDataStuff_ = com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder> staticDataStuffBuilder_;
      public boolean hasStaticDataStuff() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto getStaticDataStuff() {
        if (staticDataStuffBuilder_ == null) {
          return staticDataStuff_;
        } else {
          return staticDataStuffBuilder_.getMessage();
        }
      }
      public Builder setStaticDataStuff(com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto value) {
        if (staticDataStuffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          staticDataStuff_ = value;
          onChanged();
        } else {
          staticDataStuffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setStaticDataStuff(
          com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder builderForValue) {
        if (staticDataStuffBuilder_ == null) {
          staticDataStuff_ = builderForValue.build();
          onChanged();
        } else {
          staticDataStuffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeStaticDataStuff(com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto value) {
        if (staticDataStuffBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              staticDataStuff_ != com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.getDefaultInstance()) {
            staticDataStuff_ =
              com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.newBuilder(staticDataStuff_).mergeFrom(value).buildPartial();
          } else {
            staticDataStuff_ = value;
          }
          onChanged();
        } else {
          staticDataStuffBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearStaticDataStuff() {
        if (staticDataStuffBuilder_ == null) {
          staticDataStuff_ = com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.getDefaultInstance();
          onChanged();
        } else {
          staticDataStuffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder getStaticDataStuffBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStaticDataStuffFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder getStaticDataStuffOrBuilder() {
        if (staticDataStuffBuilder_ != null) {
          return staticDataStuffBuilder_.getMessageOrBuilder();
        } else {
          return staticDataStuff_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder> 
          getStaticDataStuffFieldBuilder() {
        if (staticDataStuffBuilder_ == null) {
          staticDataStuffBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProto.Builder, com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.StaticDataProtoOrBuilder>(
                  staticDataStuff_,
                  getParentForChildren(),
                  isClean());
          staticDataStuff_ = null;
        }
        return staticDataStuffBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.PurgeClientStaticDataResponseProto)
    }
    
    static {
      defaultInstance = new PurgeClientStaticDataResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.PurgeClientStaticDataResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PurgeClientStaticDataResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PurgeClientStaticDataResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EventStaticData.proto\022\005proto\032\020StaticDa" +
      "ta.proto\"g\n\"PurgeClientStaticDataRespons" +
      "eProto\022\020\n\010senderId\030\001 \001(\005\022/\n\017staticDataSt" +
      "uff\030\002 \001(\0132\026.proto.StaticDataProtoB5\n\035com" +
      ".lvl6.mobsters.eventprotosB\024EventStaticD" +
      "ataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_PurgeClientStaticDataResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_PurgeClientStaticDataResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_PurgeClientStaticDataResponseProto_descriptor,
              new java.lang.String[] { "SenderId", "StaticDataStuff", },
              com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.class,
              com.lvl6.mobsters.eventprotos.EventStaticDataProto.PurgeClientStaticDataResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.StaticDataStuffProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
