// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartupEvent.proto

package com.lvl6.mobsters.eventprotos;

public final class StartupEventProto {
  private StartupEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StartupRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional .proto.StartupRequestProto.LoginType loginType = 2;
    boolean hasLoginType();
    com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType getLoginType();
  }
  public static final class StartupRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements StartupRequestProtoOrBuilder {
    // Use StartupRequestProto.newBuilder() to construct.
    private StartupRequestProto(Builder builder) {
      super(builder);
    }
    private StartupRequestProto(boolean noInit) {}
    
    private static final StartupRequestProto defaultInstance;
    public static StartupRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public StartupRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupRequestProto_fieldAccessorTable;
    }
    
    public enum LoginType
        implements com.google.protobuf.ProtocolMessageEnum {
      GAME_CENTER_ID(0, 0),
      UDID(1, 1),
      ;
      
      public static final int GAME_CENTER_ID_VALUE = 0;
      public static final int UDID_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static LoginType valueOf(int value) {
        switch (value) {
          case 0: return GAME_CENTER_ID;
          case 1: return UDID;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<LoginType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LoginType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LoginType>() {
              public LoginType findValueByNumber(int number) {
                return LoginType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final LoginType[] VALUES = {
        GAME_CENTER_ID, UDID, 
      };
      
      public static LoginType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private LoginType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.StartupRequestProto.LoginType)
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional .proto.StartupRequestProto.LoginType loginType = 2;
    public static final int LOGINTYPE_FIELD_NUMBER = 2;
    private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType loginType_;
    public boolean hasLoginType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType getLoginType() {
      return loginType_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      loginType_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType.GAME_CENTER_ID;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, loginType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, loginType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        loginType_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType.GAME_CENTER_ID;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto build() {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto buildPartial() {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto result = new com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginType_ = loginType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto other) {
        if (other == com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasLoginType()) {
          setLoginType(other.getLoginType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType value = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                loginType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional .proto.StartupRequestProto.LoginType loginType = 2;
      private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType loginType_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType.GAME_CENTER_ID;
      public boolean hasLoginType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType getLoginType() {
        return loginType_;
      }
      public Builder setLoginType(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        loginType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginType_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.LoginType.GAME_CENTER_ID;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.StartupRequestProto)
    }
    
    static {
      defaultInstance = new StartupRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.StartupRequestProto)
  }
  
  public interface StartupResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.FullUserProto fup = 1;
    boolean hasFup();
    com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto getFup();
    com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder getFupOrBuilder();
    
    // optional int64 currentServerTime = 2;
    boolean hasCurrentServerTime();
    long getCurrentServerTime();
    
    // optional .proto.StartupResponseProto.StartupStatus status = 3;
    boolean hasStatus();
    com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus getStatus();
  }
  public static final class StartupResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements StartupResponseProtoOrBuilder {
    // Use StartupResponseProto.newBuilder() to construct.
    private StartupResponseProto(Builder builder) {
      super(builder);
    }
    private StartupResponseProto(boolean noInit) {}
    
    private static final StartupResponseProto defaultInstance;
    public static StartupResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public StartupResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupResponseProto_fieldAccessorTable;
    }
    
    public enum StartupStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS_GAME_CENTER_ID(0, 0),
      SUCCESS_UDID(1, 1),
      SUCCESS_NEW_USER(2, 2),
      FAIL_OTHER(3, 4),
      ;
      
      public static final int SUCCESS_GAME_CENTER_ID_VALUE = 0;
      public static final int SUCCESS_UDID_VALUE = 1;
      public static final int SUCCESS_NEW_USER_VALUE = 2;
      public static final int FAIL_OTHER_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static StartupStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS_GAME_CENTER_ID;
          case 1: return SUCCESS_UDID;
          case 2: return SUCCESS_NEW_USER;
          case 4: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<StartupStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StartupStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StartupStatus>() {
              public StartupStatus findValueByNumber(int number) {
                return StartupStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final StartupStatus[] VALUES = {
        SUCCESS_GAME_CENTER_ID, SUCCESS_UDID, SUCCESS_NEW_USER, FAIL_OTHER, 
      };
      
      public static StartupStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private StartupStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.StartupResponseProto.StartupStatus)
    }
    
    private int bitField0_;
    // optional .proto.FullUserProto fup = 1;
    public static final int FUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto fup_;
    public boolean hasFup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto getFup() {
      return fup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder getFupOrBuilder() {
      return fup_;
    }
    
    // optional int64 currentServerTime = 2;
    public static final int CURRENTSERVERTIME_FIELD_NUMBER = 2;
    private long currentServerTime_;
    public boolean hasCurrentServerTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCurrentServerTime() {
      return currentServerTime_;
    }
    
    // optional .proto.StartupResponseProto.StartupStatus status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      fup_ = com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance();
      currentServerTime_ = 0L;
      status_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasFup()) {
        if (!getFup().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, fup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, currentServerTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, currentServerTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.internal_static_proto_StartupResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (fupBuilder_ == null) {
          fup_ = com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance();
        } else {
          fupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        currentServerTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto build() {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto buildPartial() {
        com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto result = new com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (fupBuilder_ == null) {
          result.fup_ = fup_;
        } else {
          result.fup_ = fupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currentServerTime_ = currentServerTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto other) {
        if (other == com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.getDefaultInstance()) return this;
        if (other.hasFup()) {
          mergeFup(other.getFup());
        }
        if (other.hasCurrentServerTime()) {
          setCurrentServerTime(other.getCurrentServerTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasFup()) {
          if (!getFup().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.newBuilder();
              if (hasFup()) {
                subBuilder.mergeFrom(getFup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentServerTime_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus value = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.FullUserProto fup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto fup_ = com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder> fupBuilder_;
      public boolean hasFup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto getFup() {
        if (fupBuilder_ == null) {
          return fup_;
        } else {
          return fupBuilder_.getMessage();
        }
      }
      public Builder setFup(com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto value) {
        if (fupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fup_ = value;
          onChanged();
        } else {
          fupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setFup(
          com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder builderForValue) {
        if (fupBuilder_ == null) {
          fup_ = builderForValue.build();
          onChanged();
        } else {
          fupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeFup(com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto value) {
        if (fupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              fup_ != com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance()) {
            fup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.newBuilder(fup_).mergeFrom(value).buildPartial();
          } else {
            fup_ = value;
          }
          onChanged();
        } else {
          fupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearFup() {
        if (fupBuilder_ == null) {
          fup_ = com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.getDefaultInstance();
          onChanged();
        } else {
          fupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder getFupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder getFupOrBuilder() {
        if (fupBuilder_ != null) {
          return fupBuilder_.getMessageOrBuilder();
        } else {
          return fup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder> 
          getFupFieldBuilder() {
        if (fupBuilder_ == null) {
          fupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.FullUserProtoOrBuilder>(
                  fup_,
                  getParentForChildren(),
                  isClean());
          fup_ = null;
        }
        return fupBuilder_;
      }
      
      // optional int64 currentServerTime = 2;
      private long currentServerTime_ ;
      public boolean hasCurrentServerTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCurrentServerTime() {
        return currentServerTime_;
      }
      public Builder setCurrentServerTime(long value) {
        bitField0_ |= 0x00000002;
        currentServerTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentServerTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentServerTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .proto.StartupResponseProto.StartupStatus status = 3;
      private com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus status_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.StartupResponseProto)
    }
    
    static {
      defaultInstance = new StartupResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.StartupResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StartupRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StartupRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StartupResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StartupResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StartupEvent.proto\022\005proto\032\023FullUserPro" +
      "to.proto\"\237\001\n\023StartupRequestProto\022$\n\003mup\030" +
      "\001 \001(\0132\027.proto.MinimumUserProto\0227\n\tloginT" +
      "ype\030\002 \001(\0162$.proto.StartupRequestProto.Lo" +
      "ginType\")\n\tLoginType\022\022\n\016GAME_CENTER_ID\020\000" +
      "\022\010\n\004UDID\020\001\"\364\001\n\024StartupResponseProto\022!\n\003f" +
      "up\030\001 \001(\0132\024.proto.FullUserProto\022\031\n\021curren" +
      "tServerTime\030\002 \001(\003\0229\n\006status\030\003 \001(\0162).prot" +
      "o.StartupResponseProto.StartupStatus\"c\n\r" +
      "StartupStatus\022\032\n\026SUCCESS_GAME_CENTER_ID\020",
      "\000\022\020\n\014SUCCESS_UDID\020\001\022\024\n\020SUCCESS_NEW_USER\020" +
      "\002\022\016\n\nFAIL_OTHER\020\004B.\n\031com.lvl6.aoc2.event" +
      "protosB\021StartupEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_StartupRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_StartupRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_StartupRequestProto_descriptor,
              new java.lang.String[] { "Mup", "LoginType", },
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.class,
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupRequestProto.Builder.class);
          internal_static_proto_StartupResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_StartupResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_StartupResponseProto_descriptor,
              new java.lang.String[] { "Fup", "CurrentServerTime", "Status", },
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.class,
              com.lvl6.mobsters.eventprotos.StartupEventProto.StartupResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.FullUser.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
