// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserDungeonStatusHistoryProto.proto

package com.lvl6.mobsters.eventprotos;

public final class UserDungeonStatusHistoryProto {
  private UserDungeonStatusHistoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserDungeonStatusHistoryRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional int32 userHp = 2;
    boolean hasUserHp();
    int getUserHp();
    
    // optional int32 userMana = 3;
    boolean hasUserMana();
    int getUserMana();
    
    // optional int32 actionsPerformed = 4;
    boolean hasActionsPerformed();
    int getActionsPerformed();
    
    // optional string dungeonRoomName = 5;
    boolean hasDungeonRoomName();
    String getDungeonRoomName();
  }
  public static final class UserDungeonStatusHistoryRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements UserDungeonStatusHistoryRequestProtoOrBuilder {
    // Use UserDungeonStatusHistoryRequestProto.newBuilder() to construct.
    private UserDungeonStatusHistoryRequestProto(Builder builder) {
      super(builder);
    }
    private UserDungeonStatusHistoryRequestProto(boolean noInit) {}
    
    private static final UserDungeonStatusHistoryRequestProto defaultInstance;
    public static UserDungeonStatusHistoryRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserDungeonStatusHistoryRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional int32 userHp = 2;
    public static final int USERHP_FIELD_NUMBER = 2;
    private int userHp_;
    public boolean hasUserHp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getUserHp() {
      return userHp_;
    }
    
    // optional int32 userMana = 3;
    public static final int USERMANA_FIELD_NUMBER = 3;
    private int userMana_;
    public boolean hasUserMana() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getUserMana() {
      return userMana_;
    }
    
    // optional int32 actionsPerformed = 4;
    public static final int ACTIONSPERFORMED_FIELD_NUMBER = 4;
    private int actionsPerformed_;
    public boolean hasActionsPerformed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getActionsPerformed() {
      return actionsPerformed_;
    }
    
    // optional string dungeonRoomName = 5;
    public static final int DUNGEONROOMNAME_FIELD_NUMBER = 5;
    private java.lang.Object dungeonRoomName_;
    public boolean hasDungeonRoomName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getDungeonRoomName() {
      java.lang.Object ref = dungeonRoomName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dungeonRoomName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDungeonRoomNameBytes() {
      java.lang.Object ref = dungeonRoomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dungeonRoomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      userHp_ = 0;
      userMana_ = 0;
      actionsPerformed_ = 0;
      dungeonRoomName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userHp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userMana_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, actionsPerformed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDungeonRoomNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userHp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userMana_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, actionsPerformed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDungeonRoomNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        userHp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userMana_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        actionsPerformed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        dungeonRoomName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto build() {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto buildPartial() {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto result = new com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userHp_ = userHp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userMana_ = userMana_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.actionsPerformed_ = actionsPerformed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dungeonRoomName_ = dungeonRoomName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto other) {
        if (other == com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasUserHp()) {
          setUserHp(other.getUserHp());
        }
        if (other.hasUserMana()) {
          setUserMana(other.getUserMana());
        }
        if (other.hasActionsPerformed()) {
          setActionsPerformed(other.getActionsPerformed());
        }
        if (other.hasDungeonRoomName()) {
          setDungeonRoomName(other.getDungeonRoomName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userHp_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userMana_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              actionsPerformed_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              dungeonRoomName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional int32 userHp = 2;
      private int userHp_ ;
      public boolean hasUserHp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getUserHp() {
        return userHp_;
      }
      public Builder setUserHp(int value) {
        bitField0_ |= 0x00000002;
        userHp_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserHp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userHp_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 userMana = 3;
      private int userMana_ ;
      public boolean hasUserMana() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getUserMana() {
        return userMana_;
      }
      public Builder setUserMana(int value) {
        bitField0_ |= 0x00000004;
        userMana_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserMana() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userMana_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 actionsPerformed = 4;
      private int actionsPerformed_ ;
      public boolean hasActionsPerformed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getActionsPerformed() {
        return actionsPerformed_;
      }
      public Builder setActionsPerformed(int value) {
        bitField0_ |= 0x00000008;
        actionsPerformed_ = value;
        onChanged();
        return this;
      }
      public Builder clearActionsPerformed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        actionsPerformed_ = 0;
        onChanged();
        return this;
      }
      
      // optional string dungeonRoomName = 5;
      private java.lang.Object dungeonRoomName_ = "";
      public boolean hasDungeonRoomName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDungeonRoomName() {
        java.lang.Object ref = dungeonRoomName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dungeonRoomName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDungeonRoomName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dungeonRoomName_ = value;
        onChanged();
        return this;
      }
      public Builder clearDungeonRoomName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dungeonRoomName_ = getDefaultInstance().getDungeonRoomName();
        onChanged();
        return this;
      }
      void setDungeonRoomName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        dungeonRoomName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.UserDungeonStatusHistoryRequestProto)
    }
    
    static {
      defaultInstance = new UserDungeonStatusHistoryRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.UserDungeonStatusHistoryRequestProto)
  }
  
  public interface UserDungeonStatusHistoryResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.MinimumUserProto mup = 1;
    boolean hasMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup();
    com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder();
    
    // optional .proto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus status = 2;
    boolean hasStatus();
    com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus getStatus();
  }
  public static final class UserDungeonStatusHistoryResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements UserDungeonStatusHistoryResponseProtoOrBuilder {
    // Use UserDungeonStatusHistoryResponseProto.newBuilder() to construct.
    private UserDungeonStatusHistoryResponseProto(Builder builder) {
      super(builder);
    }
    private UserDungeonStatusHistoryResponseProto(boolean noInit) {}
    
    private static final UserDungeonStatusHistoryResponseProto defaultInstance;
    public static UserDungeonStatusHistoryResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserDungeonStatusHistoryResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryResponseProto_fieldAccessorTable;
    }
    
    public enum UserDungeonStatusHistoryStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS(0, 0),
      FAIL_NEGATIVE_HP_OR_MANA(1, 1),
      FAIL_NO_ACTIONS_PERFORMED(2, 2),
      FAIL_NO_MONSTERS_DEFEATED(3, 3),
      FAIL_OTHER(4, 4),
      ;
      
      public static final int SUCCESS_VALUE = 0;
      public static final int FAIL_NEGATIVE_HP_OR_MANA_VALUE = 1;
      public static final int FAIL_NO_ACTIONS_PERFORMED_VALUE = 2;
      public static final int FAIL_NO_MONSTERS_DEFEATED_VALUE = 3;
      public static final int FAIL_OTHER_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static UserDungeonStatusHistoryStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL_NEGATIVE_HP_OR_MANA;
          case 2: return FAIL_NO_ACTIONS_PERFORMED;
          case 3: return FAIL_NO_MONSTERS_DEFEATED;
          case 4: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<UserDungeonStatusHistoryStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<UserDungeonStatusHistoryStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserDungeonStatusHistoryStatus>() {
              public UserDungeonStatusHistoryStatus findValueByNumber(int number) {
                return UserDungeonStatusHistoryStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final UserDungeonStatusHistoryStatus[] VALUES = {
        SUCCESS, FAIL_NEGATIVE_HP_OR_MANA, FAIL_NO_ACTIONS_PERFORMED, FAIL_NO_MONSTERS_DEFEATED, FAIL_OTHER, 
      };
      
      public static UserDungeonStatusHistoryStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private UserDungeonStatusHistoryStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus)
    }
    
    private int bitField0_;
    // optional .proto.MinimumUserProto mup = 1;
    public static final int MUP_FIELD_NUMBER = 1;
    private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_;
    public boolean hasMup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
      return mup_;
    }
    public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
      return mup_;
    }
    
    // optional .proto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      status_ = com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mup_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.internal_static_proto_UserDungeonStatusHistoryResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.getDescriptor();
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto getDefaultInstanceForType() {
        return com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto build() {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto buildPartial() {
        com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto result = new com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mupBuilder_ == null) {
          result.mup_ = mup_;
        } else {
          result.mup_ = mupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto) {
          return mergeFrom((com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto other) {
        if (other == com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.getDefaultInstance()) return this;
        if (other.hasMup()) {
          mergeMup(other.getMup());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder subBuilder = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder();
              if (hasMup()) {
                subBuilder.mergeFrom(getMup());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMup(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus value = com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.MinimumUserProto mup = 1;
      private com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> mupBuilder_;
      public boolean hasMup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto getMup() {
        if (mupBuilder_ == null) {
          return mup_;
        } else {
          return mupBuilder_.getMessage();
        }
      }
      public Builder setMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mup_ = value;
          onChanged();
        } else {
          mupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMup(
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder builderForValue) {
        if (mupBuilder_ == null) {
          mup_ = builderForValue.build();
          onChanged();
        } else {
          mupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMup(com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto value) {
        if (mupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mup_ != com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance()) {
            mup_ =
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.newBuilder(mup_).mergeFrom(value).buildPartial();
          } else {
            mup_ = value;
          }
          onChanged();
        } else {
          mupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMup() {
        if (mupBuilder_ == null) {
          mup_ = com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          mupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder getMupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMupFieldBuilder().getBuilder();
      }
      public com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder getMupOrBuilder() {
        if (mupBuilder_ != null) {
          return mupBuilder_.getMessageOrBuilder();
        } else {
          return mup_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder> 
          getMupFieldBuilder() {
        if (mupBuilder_ == null) {
          mupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProto.Builder, com.lvl6.mobsters.noneventprotos.FullUser.MinimumUserProtoOrBuilder>(
                  mup_,
                  getParentForChildren(),
                  isClean());
          mup_ = null;
        }
        return mupBuilder_;
      }
      
      // optional .proto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus status = 2;
      private com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus status_ = com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus.SUCCESS;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.UserDungeonStatusHistoryStatus.SUCCESS;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.UserDungeonStatusHistoryResponseProto)
    }
    
    static {
      defaultInstance = new UserDungeonStatusHistoryResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.UserDungeonStatusHistoryResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserDungeonStatusHistoryRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_UserDungeonStatusHistoryRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserDungeonStatusHistoryResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_UserDungeonStatusHistoryResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#UserDungeonStatusHistoryProto.proto\022\005p" +
      "roto\032\023FullUserProto.proto\"\241\001\n$UserDungeo" +
      "nStatusHistoryRequestProto\022$\n\003mup\030\001 \001(\0132" +
      "\027.proto.MinimumUserProto\022\016\n\006userHp\030\002 \001(\005" +
      "\022\020\n\010userMana\030\003 \001(\005\022\030\n\020actionsPerformed\030\004" +
      " \001(\005\022\027\n\017dungeonRoomName\030\005 \001(\t\"\306\002\n%UserDu" +
      "ngeonStatusHistoryResponseProto\022$\n\003mup\030\001" +
      " \001(\0132\027.proto.MinimumUserProto\022[\n\006status\030" +
      "\002 \001(\0162K.proto.UserDungeonStatusHistoryRe" +
      "sponseProto.UserDungeonStatusHistoryStat",
      "us\"\231\001\n\036UserDungeonStatusHistoryStatus\022\013\n" +
      "\007SUCCESS\020\000\022\034\n\030FAIL_NEGATIVE_HP_OR_MANA\020\001" +
      "\022\035\n\031FAIL_NO_ACTIONS_PERFORMED\020\002\022\035\n\031FAIL_" +
      "NO_MONSTERS_DEFEATED\020\003\022\016\n\nFAIL_OTHER\020\004B:" +
      "\n\031com.lvl6.aoc2.eventprotosB\035UserDungeon" +
      "StatusHistoryProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_UserDungeonStatusHistoryRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_UserDungeonStatusHistoryRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_UserDungeonStatusHistoryRequestProto_descriptor,
              new java.lang.String[] { "Mup", "UserHp", "UserMana", "ActionsPerformed", "DungeonRoomName", },
              com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.class,
              com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryRequestProto.Builder.class);
          internal_static_proto_UserDungeonStatusHistoryResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_UserDungeonStatusHistoryResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_UserDungeonStatusHistoryResponseProto_descriptor,
              new java.lang.String[] { "Mup", "Status", },
              com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.class,
              com.lvl6.mobsters.eventprotos.UserDungeonStatusHistoryProto.UserDungeonStatusHistoryResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.mobsters.noneventprotos.FullUser.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
